config/routes.rb
Jaunt::Application.routes.draw do
  resources :tripitems

  resources :trips

  root to: 'main#home'

  get '/:slug', to: 'trips#show'

  

end

app/models/trip.rb
class Trip < ActiveRecord::Base

	before_create :set_slug

	has_many :tripitems

	def set_slug
		require 'uuidtools'
		require 'base64'
		self.slug = Base64.encode64(UUIDTools::UUID.random_create)[0..8]
	end

end

app/models/tripitem.rb
class Tripitem < ActiveRecord::Base
	belongs_to :trip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def home
	end
end

app/controllers/tripitems_controller.rb
class TripitemsController < ApplicationController
  before_action :set_tripitem, only: [:show, :edit, :update, :destroy]

  # GET /tripitems
  # GET /tripitems.json
  def index
    @tripitems = Tripitem.all
  end

  # GET /tripitems/1
  # GET /tripitems/1.json
  def show
  end

  # GET /tripitems/new
  def new
    @tripitem = Tripitem.new
  end

  # GET /tripitems/1/edit
  def edit
  end

  # POST /tripitems
  # POST /tripitems.json
  def create
    @tripitem = Tripitem.new(tripitem_params)

    respond_to do |format|
      if @tripitem.save
        format.html { redirect_to @tripitem, notice: 'Tripitem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tripitem }
      else
        format.html { render action: 'new' }
        format.json { render json: @tripitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tripitems/1
  # PATCH/PUT /tripitems/1.json
  def update
    respond_to do |format|
      if @tripitem.update(tripitem_params)
        format.html { redirect_to @tripitem, notice: 'Tripitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tripitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tripitems/1
  # DELETE /tripitems/1.json
  def destroy
    @tripitem.destroy
    respond_to do |format|
      format.html { redirect_to tripitems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tripitem
      @tripitem = Tripitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tripitem_params
      params.require(:tripitem).permit(:trip_id, :description, :location, :start_time, :end_time)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find_by_slug(params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title, :description, :arrive_time, :user_id, :return_time, :destination, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tripitems_helper.rb
module TripitemsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jaunt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/home.html.erb
<h1>Jaunt</h1>

app/views/tripitems/_form.html.erb
<%= form_for(@tripitem) do |f| %>
  <% if @tripitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tripitem.errors.count, "error") %> prohibited this tripitem from being saved:</h2>

      <ul>
      <% @tripitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.number_field :trip_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tripitems/edit.html.erb
<h1>Editing tripitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @tripitem %> |
<%= link_to 'Back', tripitems_path %>

app/views/tripitems/index.html.erb
<h1>Listing tripitems</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start time</th>
      <th>End time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tripitems.each do |tripitem| %>
      <tr>
        <td><%= tripitem.trip_id %></td>
        <td><%= tripitem.description %></td>
        <td><%= tripitem.location %></td>
        <td><%= tripitem.start_time %></td>
        <td><%= tripitem.end_time %></td>
        <td><%= link_to 'Show', tripitem %></td>
        <td><%= link_to 'Edit', edit_tripitem_path(tripitem) %></td>
        <td><%= link_to 'Destroy', tripitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tripitem', new_tripitem_path %>

app/views/tripitems/new.html.erb
<h1>New tripitem</h1>

<%= render 'form' %>

<%= link_to 'Back', tripitems_path %>

app/views/tripitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip:</strong>
  <%= @tripitem.trip_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tripitem.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @tripitem.location %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @tripitem.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @tripitem.end_time %>
</p>

<%= link_to 'Edit', edit_tripitem_path(@tripitem) %> |
<%= link_to 'Back', tripitems_path %>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :arrive_time %><br>
    <%= f.text_field :arrive_time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :return_time %><br>
    <%= f.text_field :return_time %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Arrive time</th>
      <th>User</th>
      <th>Return time</th>
      <th>Destination</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.title %></td>
        <td><%= trip.description %></td>
        <td><%= trip.arrive_time %></td>
        <td><%= trip.user_id %></td>
        <td><%= trip.return_time %></td>
        <td><%= trip.destination %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @trip.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trip.description %>
</p>

<p>
  <strong>Arrive time:</strong>
  <%= @trip.arrive_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @trip.user_id %>
</p>

<p>
  <strong>Return time:</strong>
  <%= @trip.return_time %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @trip.destination %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>